name: release zcm(Zenn Contents Manager)
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - run: |
          mv target/release/zcm .

          git config user.email "sek.ohei.w0822@icloud.com"
          git config user.name "gh actions"
          git switch -c release/v0.1
          git rm -r --cached --ignore-unmatch * .*
          git add articles images zcm
          git commit -m "create release"
          git push origin --force release/v0.1
